import type { GroverExperimentConfig, QiskitExportOptions } from './types';

/**
 * Dynamically generates executable Qiskit Python code for the active experiment configuration.
 */
export function generateQiskitCode(
  config: GroverExperimentConfig,
  options: QiskitExportOptions = { includeImports: true, includeComments: true, style: 'basic' }
): string {
  const { numQubits, targetStates, iterations, shots } = config;
  const targetsFormatted = targetStates.map((t) => `'${t}'`).join(', ');

  if (options.style === 'grover_operator') {
    return `# Qiskit 1.x — Grover's Search Algorithm (Using Qiskit Circuit Library)
# Generated by GroverLab (https://groverlab.quantum)

from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector
from qiskit.circuit.library import GroverOperator
from qiskit_aer import AerSimulator
import matplotlib.pyplot as plt

# 1. Configuration
num_qubits = ${numQubits}
target_states = [${targetsFormatted}]
iterations = ${iterations}
shots = ${shots}

# 2. Build Oracle Statevector
# Mark target states with phase flip (-1)
oracle_matrix = Statevector.from_label('0' * num_qubits).data
for i in range(2**num_qubits):
    binary = format(i, f'0{num_qubits}b')
    if binary in target_states:
        oracle_matrix[i] = -oracle_matrix[i]

oracle_circuit = QuantumCircuit(num_qubits)
# Define Custom Phase Oracle Gate
oracle_gate = QuantumCircuit(num_qubits, name="U_oracle")
# Invert phase of target states
for target in target_states:
    # Apply X gates to map target to |11...1>
    for q in range(num_qubits):
        if target[num_qubits - 1 - q] == '0':
            oracle_gate.x(q)
    # Multi-controlled Z gate
    if num_qubits == 2:
        oracle_gate.cz(0, 1)
    elif num_qubits == 3:
        oracle_gate.mcz([0, 1], 2)
    elif num_qubits == 4:
        oracle_gate.mcz([0, 1, 2], 3)
    # Revert X gates
    for q in range(num_qubits):
        if target[num_qubits - 1 - q] == '0':
            oracle_gate.x(q)

# 3. Construct Grover Operator (Oracle + Diffusion)
grover_op = GroverOperator(oracle_gate)

# 4. Assemble Full Circuit
qc = QuantumCircuit(num_qubits, num_qubits)
# Step A: Uniform Superposition (H^⊗n)
qc.h(range(num_qubits))

# Step B: Repeat Grover Operator k times
for _ in range(iterations):
    qc.append(grover_op, range(num_qubits))

# Step C: Measurement
qc.measure(range(num_qubits), range(num_qubits))

# 5. Run Simulation using AerSimulator
backend = AerSimulator()
result = backend.run(qc, shots=shots).result()
counts = result.get_counts()

print("Measurement Counts:", counts)
`;
  }

  // Explicit Gate Construction (Basic Style)
  return `# Qiskit 1.x — Grover's Search Algorithm (Explicit Gate Construction)
# Qubits: ${numQubits} | Target States: ${targetStates.map((s) => '|' + s + '⟩').join(', ')} | Iterations: ${iterations}

from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator

def build_oracle(n_qubits, targets):
    qc = QuantumCircuit(n_qubits, name="Oracle (U_w)")
    for target in targets:
        # Flip zero bits to target 1s for multi-controlled Z
        for q in range(n_qubits):
            # Qiskit uses little-endian qubit indexing
            bit_val = target[n_qubits - 1 - q]
            if bit_val == '0':
                qc.x(q)
        
        # Apply Multi-Controlled Z (MCZ)
        if n_qubits == 2:
            qc.cz(0, 1)
        elif n_qubits == 3:
            qc.mcz([0, 1], 2)
        elif n_qubits == 4:
            qc.mcz([0, 1, 2], 3)
            
        # Uncompute X gates
        for q in range(n_qubits):
            bit_val = target[n_qubits - 1 - q]
            if bit_val == '0':
                qc.x(q)
    return qc.to_gate()

def build_diffuser(n_qubits):
    qc = QuantumCircuit(n_qubits, name="Diffuser (U_s)")
    # H^⊗n transform
    qc.h(range(n_qubits))
    # X^⊗n transform
    qc.x(range(n_qubits))
    
    # Phase shift |11...1>
    if n_qubits == 2:
        qc.cz(0, 1)
    elif n_qubits == 3:
        qc.mcz([0, 1], 2)
    elif n_qubits == 4:
        qc.mcz([0, 1, 2], 3)
        
    # Uncompute X^⊗n and H^⊗n
    qc.x(range(n_qubits))
    qc.h(range(n_qubits))
    return qc.to_gate()

# Build Main Circuit
n = ${numQubits}
k = ${iterations}
targets = [${targetsFormatted}]

qc = QuantumCircuit(n, n)

# 1. State Initialization: H^⊗n
qc.h(range(n))
qc.barrier()

# 2. Grover Iteration Loop (k times)
oracle = build_oracle(n, targets)
diffuser = build_diffuser(n)

for i in range(k):
    qc.append(oracle, range(n))
    qc.append(diffuser, range(n))
    qc.barrier()

# 3. Measurement
qc.measure(range(n), range(n))

# 4. Simulation Execution
backend = AerSimulator()
job = backend.run(qc, shots=${shots})
counts = job.result().get_counts()

print(f"Results across {${shots}} shots:")
for state, count in sorted(counts.items(), key=lambda x: x[1], reverse=True):
    print(f"  |{state}⟩: {count} shots ({count/${shots} * 100:.1f}%)")
`;
}
